#! bin/bash
# 更新下载软件包
sudo apt-get update
sudo apt-get upgrade
# 安装python3依赖环境
sudo apt-get install -y make cmake zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils build-essential libssl-dev libffi-dev python3-dev python3-venv

# 下载解压缩python3
mkdir ~/py3
cd ~/py3
wget https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tgz #若不是最新请更新路径
tar -xzvf Python-3.7.4.tgz #若更新压缩包，请更换压缩包名

# 配置Python3安装路径
cd Python-3.7.4
sudo mkdir /usr/local/python3
./configure --prefix=/usr/local/python3/

# 安装Python3
make
sudo make install
cd ..
sudo rm -rf py3

# 创建软连接
sudo rm -rf /usr/bin/python3
sudo rm -rf /usr/bin/pip3
ln -s /usr/local/python3/bin/python3.7 /usr/bin/python3
ln -s /usr/local/python3/bin/pip3.7 /usr/bin/pip3

# pip3换源
mkdir ~/.pip
echo '[global]
index-url = https://mirrors.aliyun.com/pypi/simple
#清华：https://pypi.tuna.tsinghua.edu.cn/simple
#中科大：https://pypi.mirrors.ustc.edu.cn/simple/
#华中理工大学：http://pypi.hustunique.com/
#山东理工大学：http://pypi.sdutlinux.org/
#豆瓣：http://pypi.douban.com/simple/'>>~/.pip/pip.conf
